services:
  client:
    build: .
    depends_on:
      - database

  database:
    image: oracle/database:21.3.0-xe
    environment:
      - ORACLE_PWD=oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    # healthcheck:
    #   test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/oracle@localhost:1521/XEPDB1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

